name: M1_coursework_conda_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - numpy=1.26.4
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - pandas=2.2.3
  - ipykernel=6.29.5
  - pip=24.3.1
  - pip:
      - tensorflow-macos==2.16.2
      - tensorflow-metal==1.1.0
      - optuna==4.1.0